CREATE TABLE IF NOT EXISTS f1_plataform_data.bronze.meetings (
    circuit_key INT,
    circuit_image STRING,
    circuit_info_url STRING,
    circuit_short_name STRING,
    circuit_type STRING,
    country_code STRING,
    country_flag STRING,
    country_key INT,
    country_name STRING,
    date_end STRING,
    date_start STRING,
    gmt_offset STRING,
    is_cancelled BOOLEAN,
    location STRING,
    meeting_key INT,
    meeting_name STRING,
    meeting_official_name STRING,
    year INT
);
